focus in parameterize_topology v1
hits-mbm-dev/grappa pull request #16
Opened 2024-03-06 10:36 UTC by ehhartmann

2024-03-06 13:41 UTC, ehhartmann commented
will require kimmdy update for Topology.get_neighbors method

2024-03-07 08:28 UTC, jmbuhr requested changes

2024-03-07 08:28 UTC, jmbuhr commented on src/grappa/utils/kimmdy_utils.py
> +            self, current_topology: Topology, focus_nrs: set = set()
(mutable default, see other reviews)

2024-03-07 12:48 UTC, LeifSeute approved these changes

2024-03-07 13:35 UTC, merged